parameters:
- name:     applicationBlueprint
  type:     string
- name:     blueprintVersion
  type:     string
- name:     modeElite
  type:     boolean
  default:  false

steps:

# -----------------------------------------------------------------------------------------------------
# PRE-PRODUCTION AUTOMATION STAGE
# -----------------------------------------------------------------------------------------------------
- script: echo 'Security CD Pre-Prod Environment Automation'
- script: echo applicationBlueprint = ${{parameters.applicationBlueprint}}
- script: echo modeElite = ${{parameters.modeElite}}