parameters:
- name:     dependsOn
  type:     object
  default:  []
- name:     applicationBlueprint
  type:     string
- name:     modeElite
  type:     boolean
  default:  false

stages:

# -----------------------------------------------------------------------------------------------------
# SECURITY AUTOMATION STAGE
# -----------------------------------------------------------------------------------------------------
- stage:         'SecurityAutomation'
  displayName:   'Security Automation (SA)'
  dependsOn:
  - ${{ each stage in parameters.dependsOn }}:
    - ${{stage}}
  pool:
    vmImage:      'ubuntu-latest'
  jobs:
  - job:          'SecurityAutomation'
    steps:
    - template:   /templates/dev-sec-ops/security-scans-auto.yml@CeBlueprints
      parameters:
        applicationBlueprint: ${{parameters.applicationBlueprint}}
        modeElite:            ${{parameters.modeElite}}