parameters:
- name:     name
  type:     string
- name:     displayName
  type:     string
- name:     config
  type:     object
  default:  []
- name:     dependsOn
  type:     object
  default:  []
- name:     applicationBlueprint
  type:     string
- name:     blueprintVersion
  type:     string
- name:     modeElite
  type:     boolean
  default:  false
stages:

# -----------------------------------------------------------------------------------------------------
# SECURITY REVIEW STAGE
# -----------------------------------------------------------------------------------------------------
- stage:         ${{parameters.name}}
  displayName:   ${{parameters.displayName}}
  ${{ if ne(length(parameters.dependsOn), 0) }}:
    dependsOn:
      - ${{ each stage in parameters.dependsOn }}:
        - ${{stage}}
  pool:
    vmImage:      ${{parameters.config.nameVM}}
  jobs:
  - deployment:   'SecurityReview'
    environment:  ${{parameters.config.envName}}
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo modeElite = ${{parameters.modeElite}}
          - script: echo applicationBlueprint = ${{parameters.applicationBlueprint}}