parameters:
- name:     name
  type:     string
- name:     displayName
  type:     string
- name:     config
  type:     object
  default:  []
- name:     applicationBlueprint
  type:     string
- name:     blueprintVersion
  type:     string
- name:     modeElite
  type:     boolean
  default:  false
- name:     dependsOn
  type:     object
  default:  []
  
stages:
# -----------------------------------------------------------------------------------------------------
# QUALITY ASSURANCE SCANS STAGE
# -----------------------------------------------------------------------------------------------------
- stage:         ${{parameters.name}}
  displayName:   ${{parameters.displayName}}
  dependsOn:
  - ${{ each stage in parameters.dependsOn }}:
    - ${{stage}}
  ${{ if ne(coalesce(parameters.config.nameVM, ''), '') }}: #910188 
    pool:
      name:      ${{coalesce(parameters.config.poolName, 'Azure Pipelines')}}
      vmImage:   ${{parameters.config.nameVM}}
  ${{ else }}:
    pool:
      name:      ${{parameters.config.namePool}}
  jobs:
  - job:          'QAAutomation'
    steps:
    # List all environment variables within this agent
    - bash: 'env | sort'
      displayName: Bootstrap Dump env variables
    
    # Inject the QA scans template into the pipeline
    - template:   /templates/qa/qa-scans-cd.yml@CeBlueprints
      parameters:
        applicationBlueprint: ${{parameters.applicationBlueprint}}
        blueprintVersion:     ${{parameters.blueprintVersion}}
        modeElite:            ${{parameters.modeElite}}