parameters:
- name:     dependsOn
  type:     object
  default:  []
- name:     applicationBlueprint
  type:     string
- name:     modeElite
  type:     boolean
  default:  false

stages:
# -----------------------------------------------------------------------------------------------------
# QUALITY ASSURANCE SCANS STAGE
# -----------------------------------------------------------------------------------------------------
- stage:         'QAScans'
  displayName:   'Quality Assurance (QA)'
  dependsOn:
  - ${{ each stage in parameters.dependsOn }}:
    - ${{stage}}
  pool:
    vmImage:      'ubuntu-latest'
  jobs:
  - job:          'SecurityScans'
    steps:
    - template:   /templates/qa/qa-scans-cd.yml@CeBlueprints
      parameters:
        applicationBlueprint: ${{parameters.applicationBlueprint}}
        modeElite:            ${{parameters.modeElite}}