parameters:
- name:     portfolioName
  type:     string
- name:     productName
  type:     string
- name:     applicationBlueprint
  type:     string
- name:     publishFolder
  type:     string
# Bootstrap optionals
- name:     verbose
  type:     boolean
  default:  false
# CI Blueprint optionals
- name:     versionSpec
  type:     string
# CD Blueprint optionals
- name:     modeElite
  type:     boolean
  default:  false

# --------------------------------------------------------------------------
# START OF BUILD and TEST STAGE
# --------------------------------------------------------------------------
stages:
- stage: ContinuousIntegration
  displayName: Continuous Integration (CI)

  # Configure the default agent pool and image to use for the pipeline
  pool:
    name:     'Azure Pipelines'
    vmImage:  'Windows-latest'
  
  jobs:
  - job: ContinuousIntegration
    steps:
    - checkout: self
      fetchDepth: 0
    - template: /templates/utilities/git-tools-git-version.yml@CeBlueprints
      parameters:
        portfolioName:    ${{parameters.portfolioName}}
        productName:      ${{parameters.productName}}
        versionSpec:      ${{parameters.versionSpec}}

# ==========================================================================
# BOOTSTRAP VALIDATION
# ==========================================================================
    - template: /templates/boot-strap.yml@CeBlueprints
      parameters:
        bootstrapMode:        'init'
        applicationType:      'other'
        applicationBlueprint: ${{parameters.applicationBlueprint}}
        portfolioName:        ${{parameters.portfolioName}}
        productName:          ${{parameters.productName}}
        sourcesDirectory:     $(Build.SourcesDirectory)
        verbose:              ${{parameters.verbose}}
        modeElite:            ${{parameters.modeElite}}
# ==========================================================================

# --------------------------------------------------------------------------
# CONTINUOUS INTEGRATION BUILD
# --------------------------------------------------------------------------

# --------------------------------------------------------------------------
# CONTINUOUS INTEGRATION TEST
# --------------------------------------------------------------------------

# --------------------------------------------------------------------------
# PUBLISH
# --------------------------------------------------------------------------
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish:  "$(Build.SourcesDirectory)/$(Build.Repository.Name)/${{parameters.publishFolder}}"
        ArtifactName:   'drop'

# ==========================================================================
# BOOTSTRAP VALIDATION
# ==========================================================================
    - template: /templates/boot-strap.yml@CeBlueprints
      parameters:
        bootstrapMode:        'run'
        applicationType:      'other'
        applicationBlueprint: ${{parameters.applicationBlueprint}}
        portfolioName:        ${{parameters.portfolioName}}
        productName:          ${{parameters.productName}}
        sourcesDirectory:     $(Build.SourcesDirectory)
        verbose:              ${{parameters.verbose}}
        modeElite:            ${{parameters.modeElite}}
# ==========================================================================
      
# --------------------------------------------------------------------------
# END BUILD AND TEST STAGE
# --------------------------------------------------------------------------

    - ${{ if eq(lower(variables['Build.SourceBranchName']), 'merge') }}:
      - script: echo CD part of the pipeline is suppressed for pull request validation builds! 
        displayName: PR Validation CD Suppression Alert