parameters:
- name:     stage
  type:     object
  
stages:

# -----------------------------------------------------------------------------------------------------
# DEVELOPMENT STAGE
# -----------------------------------------------------------------------------------------------------
- ${{ if eq(parameters.stage.development.name, 'Development') }}:
  - template: /blueprints/universal-artifact/azure-pipeline-universal-artifact-cd-stage.yml@CeBlueprints
    parameters:
      name:                           Development
      displayName:                    Development (DV)
      vmImage:                        ${{parameters.stage.development.vmImage}}
      envName:                        ${{parameters.stage.development.envName}}
      feedPublish:                    ${{parameters.stage.development.feedPublish}}
      packagePublish:                 ${{parameters.stage.development.packagePublish}}
      dependsOn:
      - ContinuousIntegration

# -----------------------------------------------------------------------------------------------------
# SYSTEM TEST STAGE
# -----------------------------------------------------------------------------------------------------
- ${{ if eq(parameters.stage.systemTest.name, 'SystemTest') }}:
  - template: /blueprints/universal-artifact/azure-pipeline-universal-artifact-cd-stage.yml@CeBlueprints
    parameters:
      name:                           SystemTest
      displayName:                    System Test (SY)
      vmImage:                        ${{parameters.stage.systemTest.vmImage}}
      envName:                        ${{parameters.stage.systemTest.envName}}
      feedPublish:                    ${{parameters.stage.systemTest.feedPublish}}
      packagePublish:                 ${{parameters.stage.systemTest.packagePublish}}
      dependsOn:
      - ContinuousIntegration
      - ${{ if eq(parameters.stage.development.name, 'Development') }}:
        - Development

# -----------------------------------------------------------------------------------------------------
# SECURITY AUTOMATION STAGE
# -----------------------------------------------------------------------------------------------------
- template: /templates/dev-sec-ops/azure-pipeline-security-auto.yml@CeBlueprints
  parameters:
    applicationBlueprint: ${{parameters.stage.securityAutomation.applicationBlueprint}}
    modeElite:            ${{parameters.stage.securityAutomation.modeElite}}
    dependsOn:
    - ContinuousIntegration
    - ${{ if eq(parameters.stage.development.name, 'Development') }}:
      - Development
    - ${{ if eq(parameters.stage.systemTest.name, 'SystemTest') }}:
      - SystemTest

# -----------------------------------------------------------------------------------------------------
# QA SCANS STAGE
# -----------------------------------------------------------------------------------------------------
- template: /templates/qa/azure-pipeline-qa-scans.yml@CeBlueprints
  parameters:
    applicationBlueprint: ${{parameters.stage.qaScans.applicationBlueprint}}
    modeElite:            ${{parameters.stage.qaScans.modeElite}}
    dependsOn:
    - ContinuousIntegration
    - ${{ if eq(parameters.stage.development.name, 'Development') }}:
      - Development
    - ${{ if eq(parameters.stage.systemTest.name, 'SystemTest') }}:
      - SystemTest


# -----------------------------------------------------------------------------------------------------
# SECURITY REVIEW STAGE
# -----------------------------------------------------------------------------------------------------
- ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
  - template: /templates/dev-sec-ops/azure-pipeline-security-review.yml@CeBlueprints
    parameters:
      applicationBlueprint: ${{parameters.stage.securityReview.applicationBlueprint}}
      stageEnvName:         ${{parameters.stage.securityReview.envName}}
      dependsOn:
      - ContinuousIntegration
      - ${{ if eq(parameters.stage.development.name, 'Development') }}:
        - Development
      - ${{ if eq(parameters.stage.systemTest.name, 'SystemTest') }}:
        - SystemTest
      - SecurityAutomation

# -----------------------------------------------------------------------------------------------------
# STAGING STAGE
# -----------------------------------------------------------------------------------------------------
- ${{ if and(eq(parameters.stage.staging.name, 'Staging'), or(eq(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))) }}:
  - template: /blueprints/universal-artifact/azure-pipeline-universal-artifact-cd-stage.yml@CeBlueprints
    parameters:
      name:                           Staging
      displayName:                    Staging (ST)
      vmImage:                        ${{parameters.stage.staging.vmImage}}
      envName:                        ${{parameters.stage.staging.envName}}
      feedPublish:                    ${{parameters.stage.staging.feedPublish}}
      packagePublish:                 ${{parameters.stage.staging.packagePublish}}
      dependsOn:
      - ContinuousIntegration
      - ${{ if eq(parameters.stage.development.name, 'Development') }}:
        - Development
      - ${{ if eq(parameters.stage.systemTest.name, 'SystemTest') }}:
        - SystemTest
      - QAScans
      - SecurityAutomation
      - SecurityReview

# -----------------------------------------------------------------------------------------------------
# PRE-PROD AUTOMATION SCANS STAGE
# -----------------------------------------------------------------------------------------------------
- ${{ if and(eq(parameters.stage.production.name, 'Production'), or(eq(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))) }}:
  - template: /templates/pre-prod/azure-pipeline-pre-prod-automation.yml@CeBlueprints
    parameters:
      applicationBlueprint: ${{parameters.stage.preProdAutomation.applicationBlueprint}}
      modeElite:            ${{parameters.stage.preProdAutomation.modeElite}}
      dependsOn:
        - ContinuousIntegration
        - ${{ if eq(parameters.stage.development.name, 'Development') }}:
          - Development
        - ${{ if eq(parameters.stage.systemTest.name, 'SystemTest') }}:
          - SystemTest
        - QAScans
        - SecurityAutomation
        - SecurityReview
        - ${{ if eq(parameters.stage.staging.name, 'Staging') }}:
          - Staging

# -----------------------------------------------------------------------------------------------------
# PRODUCTION STAGE
# -----------------------------------------------------------------------------------------------------
- ${{ if and(eq(parameters.stage.production.name, 'Production'), or(eq(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))) }}:
  - template: /blueprints/universal-artifact/azure-pipeline-universal-artifact-cd-stage.yml@CeBlueprints
    parameters:
      name:                           Production
      displayName:                    Production (PR)
      vmImage:                        ${{parameters.stage.production.vmImage}}
      envName:                        ${{parameters.stage.production.envName}}
      feedPublish:                    ${{parameters.stage.production.feedPublish}}
      packagePublish:                 ${{parameters.stage.production.packagePublish}}
      dependsOn:
      - ContinuousIntegration
      - ${{ if eq(parameters.stage.development.name, 'Development') }}:
        - Development
      - ${{ if eq(parameters.stage.systemTest.name, 'SystemTest') }}:
        - SystemTest
      - QAScans
      - SecurityAutomation
      - SecurityReview
      - ${{ if eq(parameters.stage.staging.name, 'Staging') }}:
        - Staging
      - PreProdAutomation