parameters:
- name:     name
  type:     string
- name:     displayName
  type:     string
- name:     vmImage
  type:     string
- name:     envName
  type:     string
- name:     azRmWebDeployAzureSubscription
  type:     string
- name:     azResourceGroup
  type:     string
- name:     azRmWebDeployWebAppName
  type:     string
- name:     azFuncProjectName
  type:     string
- name:     azureFunctionType
  type:     string
- name:     functionExtensionVersion
  type:     string
- name:     windowsRuntimeStack
  type:     string
- name:     linuxRuntimeStack
  type:     string
- name:     dependsOn
  type:     object
  default:  []
stages:

# -----------------------------------------------------------------------------------------------------
# STAGE
# -----------------------------------------------------------------------------------------------------

- stage:         ${{parameters.name}}
  displayName:   ${{parameters.displayName}}
  ${{ if ne(length(parameters.dependsOn), 0) }}:
    dependsOn:
      - ${{ each stage in parameters.dependsOn }}:
        - ${{stage}}
  pool:
    vmImage:     ${{parameters.vmImage}}
  jobs:
  - deployment:  ${{parameters.name}}
    environment: ${{parameters.envName}}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@2
            displayName: Deploy Azure Function
            inputs:
              azureSubscription: ${{parameters.azRmWebDeployAzureSubscription}}
              appType: ${{parameters.azureFunctionType}}
              appName: ${{parameters.azRmWebDeployWebAppName}}
              package: '$(Pipeline.Workspace)/**/${{parameters.azFuncProjectName}}.zip'
              runtimeStack: ${{parameters.linuxRuntimeStack}}
          - task: AzureCLI@2
            displayName: Set Azure Function Runtime
            inputs:
              azureSubscription: ${{parameters.azRmWebDeployAzureSubscription}}
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az functionapp config appsettings set --settings FUNCTIONS_EXTENSION_VERSION=${{parameters.functionExtensionVersion}} -g ${{parameters.azResourceGroup}} -n ${{parameters.azRmWebDeployWebAppName}}
          - task: AzureCLI@2
            displayName: Set Azure Function .Net Version - Windows
            condition: eq( '${{ parameters.azureFunctionType }}', 'functionApp')
            inputs:
              azureSubscription: ${{parameters.azRmWebDeployAzureSubscription}}
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az functionapp config set --net-framework-version ${{parameters.windowsRuntimeStack}} -g ${{parameters.azResourceGroup}} -n ${{parameters.azRmWebDeployWebAppName}}
          - task: AzureCLI@2
            displayName: Set Azure Function .Net Version - Linux
            condition: eq('${{ parameters.azureFunctionType }}', 'functionAppLinux')
            inputs:
              azureSubscription: ${{parameters.azRmWebDeployAzureSubscription}}
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az functionapp config set --name ${{parameters.azRmWebDeployWebAppName}} --resource-group ${{parameters.azResourceGroup}} --linux-fx-version "${{parameters.linuxRuntimeStack}}"
