# --------------------------------------------------------------------------
# WorkSafeBC Multi-Stage Blueprint-Based Pipeline Design Practice
# --------------------------------------------------------------------------
# See https://aka.ms/yaml for Azure DevOps Pipeline documentation
#
# Azure Function blueprint v2
# --------------------------------------------------------------------------
# HOW TO USE
#   - Copy the content of this file to 
#     'pipelines/azure-pipelines-<portfolio>-<program>-start.yml' under the 
#     root folder of your repo
#   - Look for TODO and update / fine-tune as needed
#   - In AzureDevOps.Automation.Pipeline.Configuration.v2 repo, configure
#     your associated /deploy/__TODO_PORTFOLIO__-__TODO_PRODUCT__-config.yml
#     configuration file.
# --------------------------------------------------------------------------

trigger:
  batch: true # batch changes if true; start a new build for every push if false
  branches:
    include:
    - '*' # Trigger on all branches
  paths:
    exclude:    # Excluding changes to the Readme.me file (case dependent?)
    - '/ReadMe.md'
    - '/README.md'
    - '/readme.md'
    - '/deploy/**'
    - '/pipelines/**'

resources:
  repositories:
  - repository: CeBlueprints
    type:       git
    name:       '__TODO_INSERT_AZURE_DEVOPS_NAME_HERE__/AzureDevOps.Automation.Pipeline.Templates.v2'

extends:
  template: blueprints/azure-function/azure-pipeline-azure-function-control.yml@CeBlueprints
  parameters:
    blueprintVersion:  '2.1.0'
    netCoreVersion:     '8.x'
    portfolioName:      '__TODO_PORTFOLIO__'
    productName:        '__TODO_PRODUCT__'
    azFuncProjectName:  '__TODO_AZURE_FUNCTION_PROJECT_NAME__' # e.g. CeS.Sample.AzureFunction
    azureFunctionType:  '__TODO_AZURE_FUNCTION_TYPE__'         # either 'functionApp' or 'functionAppLinux'
    suppressCD:         true # Allow engineering to do an immediate CI/build while CD is being configured
