parameters:
- name:     netCoreVersion
  type:     string
- name:     portfolioName
  type:     string
- name:     productName
  type:     string
- name:     applicationBlueprint
  type:     string
  default:  'azure-function'
- name:     azFuncProjectName
  type:     string
  default:  '*' # TODO: to be removed once this parameter is not optional
- name:     azureFunctionType
  type:     string
  default:  'functionAppLinux'
- name:     modeElite
  type:     boolean
  default:  false
# Bootstrap optionals
- name:     verbose
  type:     boolean
  default:  false
# CI Blueprint optionals
- name:     versionSpec
  type:     string
  default:  '5.11.x' # switch from 5.6.3 to 5.11.x as default
# CD Blueprint optionals
- name:     suppressCD
  type:     boolean
  default:  false

# VARIABLES
variables:
- ${{ if ne(parameters.suppressCD, true) }}:
  - template: /deploy/${{ lower(parameters.portfolioName) }}.${{ lower(parameters.productName) }}-config.yml@self

# -----------------------------------------------------------------------------------------------------
# Azure Function App Settings
# These are set for the current LTS supported versions of .Net and current Azure Function Runtime.
# NOTE: when we move to .Net 8 (LTS) and running the function in isolation mode,
#       we will need to adjust these settings. .Net 8 only supports isolated mode.
# -----------------------------------------------------------------------------------------------------
- name:  fxnExtensionVersion
  value: '~4'

- ${{ if or(eq(parameters.netCoreVersion, '6.x'), eq(parameters.netCoreVersion, '6.0.x')) }}:
  - name:  windowsDotNetVersion
    value: 'v6.0'
  - name:  linuxDotNetVersion
    value: 'DOTNET|6.0'

- ${{ if or(eq(parameters.netCoreVersion, '8.x'), eq(parameters.netCoreVersion, '8.0.x')) }}:
  - name:  windowsDotNetVersion
    value: 'v8.0'
  - name:  linuxDotNetVersion
    value: 'DOTNET-ISOLATED|8.0'

stages:

# --------------------------------------------------------------------------
# START OF PIPELINE
# --------------------------------------------------------------------------
- template: /blueprints/azure-function/azure-pipeline-azure-function-ci.yml@CeBlueprints
  parameters:
    netCoreVersion:       ${{parameters.netCoreVersion}}
    portfolioName:        ${{parameters.portfolioName}}
    productName:          ${{parameters.productName}}
    applicationBlueprint: ${{parameters.applicationBlueprint}}
    azFuncProjectName:    ${{parameters.azFuncProjectName}}
    verbose:              ${{parameters.verbose}}
    modeElite:            ${{parameters.modeElite}}
    versionSpec:          ${{parameters.versionSpec}}

# --------------------------------------------------------------------------
# DEPLOYMENT
# 2021.10.04 WS Suppress CD on "merge" so that we can use PR validation builds
# --------------------------------------------------------------------------
- ${{ if and(ne(parameters.suppressCD, true), ne(lower(variables['Build.SourceBranchName']), 'merge')) }}:
  - template: /blueprints/azure-function/azure-pipeline-azure-function-cd.yml@CeBlueprints
    parameters:
      azFuncProjectName:                  ${{parameters.azFuncProjectName}}
      azureFunctionType:                  ${{parameters.azureFunctionType}}
      functionExtensionVersion:           ${{variables.fxnExtensionVersion}}
      linuxRuntimeStack:                  ${{variables.linuxDotNetVersion}}
      windowsRuntimeStack:                ${{variables.windowsDotNetVersion}}

      stage:
        development:
          config:
            active:                       ${{variables.developmentStageActive}}
            nameEnv:                      ${{variables.developmentStageEnvName}}
            nameVM:                       ${{variables.developmentStageVmImage}}
            testData:                     ${{variables.developmentStageTestData}}
            azureSubscription:            ${{variables.developmentStageAzRmWebDeployAzureSubscription}}
            azureResourceGroup:           ${{variables.developmentStageAzResourceGroup}}
            azureAppName:                 ${{variables.developmentStageAzRmWebDeployWebAppName}}
            applicationBlueprint:         ${{parameters.applicationBlueprint}}
            modeElite:                    ${{parameters.modeElite}}

        systemTest:
          config:
            active:                       ${{variables.systemTestStageActive}}
            nameEnv:                      ${{variables.systemTestStageEnvName}}
            nameVM:                       ${{variables.systemTestStageVmImage}}
            testData:                     ${{variables.systemTesttStageTestData}}
            azureSubscription:            ${{variables.systemTestStageAzRmWebDeployAzureSubscription}}
            azureResourceGroup:           ${{variables.systemTestStageAzResourceGroup}}
            azureAppName:                 ${{variables.systemTestStageAzRmWebDeployWebAppName}}
            applicationBlueprint:         ${{parameters.applicationBlueprint}}
            modeElite:                    ${{parameters.modeElite}}

        staging:
          config:
            active:                       ${{variables.stagingStageActive}}
            nameEnv:                      ${{variables.stagingStageEnvName}}
            nameVM:                       ${{variables.stagingStageVmImage}}
            testData:                     ${{variables.stagingStageTestData}}
            azureSubscription:            ${{variables.stagingStageAzRmWebDeployAzureSubscription}}
            azureResourceGroup:           ${{variables.stagingStageAzResourceGroup}}
            azureAppName:                 ${{variables.stagingStageAzRmWebDeployWebAppName}}
            applicationBlueprint:         ${{parameters.applicationBlueprint}}
            modeElite:                    ${{parameters.modeElite}}

        production:
          config:
            active:                       ${{variables.productionStageActive}}
            nameEnv:                      ${{variables.productionStageEnvName}}
            nameVM:                       ${{variables.productionStageVmImage}}
            testData:                     ${{variables.productionStageTestData}}
            azureSubscription:            ${{variables.productionStageAzRmWebDeployAzureSubscription}}
            azureResourceGroup:           ${{variables.productionStageAzResourceGroup}}
            azureAppName:                 ${{variables.productionStageAzRmWebDeployWebAppName}}
            applicationBlueprint:         ${{parameters.applicationBlueprint}}
            modeElite:                    ${{parameters.modeElite}}

        securityReview:
          envName:                        ${{variables.securityReviewStageEnvName}}
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
        securityAutomation:
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
        qaScans:
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
        preProdAutomation:
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}

# --------------------------------------------------------------------------
# END OF PIPELINE
# --------------------------------------------------------------------------