parameters:
- name:     netCoreVersion
  type:     string
- name:     portfolioName
  type:     string
- name:     productName
  type:     string
- name:     applicationBlueprint
  type:     string
  default:  'azure-function'
- name:     azFuncProjectName
  type:     string
  default:  '*' # TODO: to be removed once this parameter is not optional
- name:     azureFunctionType
  type:     string
  default:  'functionAppLinux'
- name:     modeElite
  type:     boolean
  default:  false
# Bootstrap optionals
- name:     verbose
  type:     boolean
  default:  false
# CI Blueprint optionals
- name:     versionSpec
  type:     string
  default:  '5.11.x' # switch from 5.6.3 to 5.11.x as default
# CD Blueprint optionals
- name:     suppressCD
  type:     boolean
  default:  false

# VARIABLES
variables:
- ${{ if ne(parameters.suppressCD, true) }}:
  - template: /deploy/${{ lower(parameters.portfolioName) }}/${{ lower(parameters.productName) }}-config.yml@CeConfiguration

# -----------------------------------------------------------------------------------------------------
# Azure Function App Settings
# These are set for the current LTS supported versions of .Net and current Azure Function Runtime.
# NOTE: when we move to .Net 8 (LTS) and possibly running the function in isolation mode,
#       we will need to adjust these settings. At that point we will probably need to add a
#       parameter for in-process vs. isolated worker process (preferred)
# -----------------------------------------------------------------------------------------------------
- name:  fxnExtensionVersion
  value: '~4'
- name:  windowsDotNetVersion
  value: 'v6.0'
- name:  linuxDotNetVersion
  value: 'DOTNET|6.0'

stages:

# --------------------------------------------------------------------------
# START OF PIPELINE
# --------------------------------------------------------------------------
- template: /blueprints/azure-function/azure-pipeline-azure-function-ci.yml@CeBlueprints
  parameters:
    netCoreVersion:       ${{parameters.netCoreVersion}}
    portfolioName:        ${{parameters.portfolioName}}
    productName:          ${{parameters.productName}}
    applicationBlueprint: ${{parameters.applicationBlueprint}}
    azFuncProjectName:    ${{parameters.azFuncProjectName}}
    verbose:              ${{parameters.verbose}}
    modeElite:            ${{parameters.modeElite}}
    versionSpec:          ${{parameters.versionSpec}}

# --------------------------------------------------------------------------
# DEPLOYMENT
# 2021.10.04 WS Suppress CD on "merge" so that we can use PR validation builds
# --------------------------------------------------------------------------
- ${{ if and(ne(parameters.suppressCD, true), ne(lower(variables['Build.SourceBranchName']), 'merge')) }}:
  - template: /blueprints/azure-function/azure-pipeline-azure-function-cd.yml@CeBlueprints
    parameters:
      stage:
        azFuncProjectName:                ${{parameters.azFuncProjectName}}
        azureFunctionType:                ${{parameters.azureFunctionType}}
        functionExtensionVersion:         ${{variables.fxnExtensionVersion}}
        linuxRuntimeStack:                ${{variables.linuxDotNetVersion}}
        windowsRuntimeStack:              ${{variables.windowsDotNetVersion}}
        development:
          name:                           ${{variables.developmentStageName}}
          vmImage:                        ${{variables.developmentStageVmImage}}
          envName:                        ${{variables.developmentStageEnvName}}
          azRmWebDeployAzureSubscription: ${{variables.developmentStageAzRmWebDeployAzureSubscription}}
          azResourceGroup:                ${{variables.developmentStageAzResourceGroup}}
          azRmWebDeployWebAppName:        ${{variables.developmentStageAzRmWebDeployWebAppName}}
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
        systemTest:
          name:                           ${{variables.systemTestStageName}}
          vmImage:                        ${{variables.systemTestStageVmImage}}
          envName:                        ${{variables.systemTestStageEnvName}}
          azRmWebDeployAzureSubscription: ${{variables.systemTestStageAzRmWebDeployAzureSubscription}}
          azResourceGroup:                ${{variables.systemTestStageAzResourceGroup}}
          azRmWebDeployWebAppName:        ${{variables.systemTestStageAzRmWebDeployWebAppName}}
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
        staging:
          name:                           ${{variables.stagingStageName}}
          vmImage:                        ${{variables.stagingStageVmImage}}
          envName:                        ${{variables.stagingStageEnvName}}
          azRmWebDeployAzureSubscription: ${{variables.stagingStageAzRmWebDeployAzureSubscription}}
          azResourceGroup:                ${{variables.stagingStageAzResourceGroup}}
          azRmWebDeployWebAppName:        ${{variables.stagingStageAzRmWebDeployWebAppName}}
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
        production:
          name:                           ${{variables.productionStageName}}
          vmImage:                        ${{variables.productionStageVmImage}}
          envName:                        ${{variables.productionStageEnvName}}
          azRmWebDeployAzureSubscription: ${{variables.productionStageAzRmWebDeployAzureSubscription}}
          azResourceGroup:                ${{variables.productionStageAzResourceGroup}}
          azRmWebDeployWebAppName:        ${{variables.productionStageAzRmWebDeployWebAppName}}
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
        securityReview:
          envName:                        ${{variables.securityReviewStageEnvName}}
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
        securityAutomation:
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
        qaScans:
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
        preProdAutomation:
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}

# --------------------------------------------------------------------------
# END OF PIPELINE
# --------------------------------------------------------------------------