parameters:
- name:     name
  type:     string
- name:     displayName
  type:     string
- name:     vmImage
  type:     string
- name:     envName
  type:     string
- name:     azRmWebDeployAzureSubscription
  type:     string
- name:     azRmWebDeployWebAppName
  type:     string
- name:     azFuncProjectName
  type:     string
- name:     dependsOn
  type:     object
  default:  []

stages:

# -----------------------------------------------------------------------------------------------------
# STAGE
# -----------------------------------------------------------------------------------------------------

- stage:         ${{parameters.name}}
  displayName:   ${{parameters.displayName}}
  ${{ if ne(length(parameters.dependsOn), 0) }}:
    dependsOn:
      - ${{ each stage in parameters.dependsOn }}:
        - ${{stage}}
  pool:
    vmImage:     ${{parameters.vmImage}}
  jobs:
  - deployment:  ${{parameters.name}}
    environment: ${{parameters.envName}}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: Deploy Azure Function
            inputs:
              azureSubscription:  ${{parameters.azRmWebDeployAzureSubscription}}
              appType:            functionApp
              WebAppName:         ${{parameters.azRmWebDeployWebAppName}}
              package:            '$(Pipeline.Workspace)/**/${{parameters.azFuncProjectName}}.zip'