variables:

# -----------------------------------------------------------------------------------------------------
# Blueprint: azure-function
#
# If you are not going to use all stages, as below, you should delete the ones that you don't need.

# -----------------------------------------------------------------------------------------------------
# CI
# -----------------------------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------------------------
# Development Stage
- name:  developmentStageActive
  value: true
- name:  developmentStageEnvName
  value: '<tbd>'
- name:  developmentStageVmImage
  value: '<tbd>'
- name:  developmentStageTestData
  value: 'Development Stage Test Data'
- name:  developmentStageAzRmWebDeployAzureSubscription
  value: '<TBD>'
- name:  developmentStageAzResourceGroup
  value: '<TBD>'
- name:  developmentStageAzRmWebDeployWebAppName
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# System Test Stage
- name:  systemTestStageActive
  value: true
- name:  systemTestStageEnvName
  value: '<tbd>'
- name:  systemTestStageVmImage
  value: '<tbd>'
- name:  systemTestStageTestData
  value: 'System Test Stage Test Data'
- name:  systemTestStageAzRmWebDeployAzureSubscription
  value: '<TBD>'
- name:  systemTestStageAzResourceGroup
  value: '<TBD>'
- name:  systemTestStageAzRmWebDeployWebAppName
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Security Review Stage
- name:  securityReviewStageEnvName
  value: '<tbd>'

# -----------------------------------------------------------------------------------------------------
# Staging Stage
# -----------------------------------------------------------------------------------------------------
# Staging Stage
- name:  stagingStageActive
  value: true
- name:  stagingStageEnvName
  value: '<tbd>'
- name:  stagingStageVmImage
  value: '<tbd>'
- name:  stagingStageTestData
  value: 'Staging Stage Test Data'
- name:  stagingStageAzRmWebDeployAzureSubscription
  value: '<TBD>'
- name:  systemTestStageAzResourceGroup
  value: '<TBD>'
- name:  stagingStageAzRmWebDeployWebAppName
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Production Stage-
- name:  productionStageActive
  value: true
- name:  productionStageEnvName
  value: '<tbd>'
- name:  productionStageVmImage
  value: '<tbd>'
- name:  productionStageTestData
  value: 'Production Stage Test Data'
- name:  productionStageAzRmWebDeployAzureSubscription
  value: '<TBD>'
- name:  systemTestStageAzResourceGroup
  value: '<TBD>'
- name:  productionStageAzRmWebDeployWebAppName
  value: '<TBD>'