parameters:
- name:     netCoreVersion
  type:     string
- name:     portfolioName
  type:     string
- name:     productName
  type:     string
- name:     applicationBlueprint
  type:     string
- name:     azFuncProjectName
  type:     string
# CI Blueprint optionals
- name:     versionSpec
  type:     string
# CD Blueprint optionals
- name:     modeElite
  type:     boolean
  default:  false
- name:     verbose
  type:     boolean
  default:  false


# --------------------------------------------------------------------------
# START OF BUILD and TEST STAGE
# --------------------------------------------------------------------------
stages:
- stage: ContinuousIntegration
  displayName: Continuous Integration (CI)

  # Configure the default agent pool and image to use for the pipeline
  pool:
    name:     'Azure Pipelines'
    vmImage:  'ubuntu-latest'

  # Variables
  variables:
    buildConfiguration:   'Release'
    vstsFeed:             '__TODO_INSERT_YOUR_NUGET_FEED_HERE'
  
  jobs:
  - job: ContinuousIntegration
    steps:
    - checkout: self
      fetchDepth: 0
    - template: /templates/utilities/git-tools-git-version.yml@CeBlueprints
      parameters:
        portfolioName:    ${{parameters.portfolioName}}
        productName:      ${{parameters.productName}}
        versionSpec:      ${{parameters.versionSpec}}

# --------------------------------------------------------------------------
# PREREQUISITES
# --------------------------------------------------------------------------
    - task: UseDotNet@2 
      displayName:      'Use .NET Core ${{parameters.netCoreVersion}}'
      inputs:
        version:        ${{parameters.netCoreVersion}}
        packageType:    sdk

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command:    restore
        projects:   '**/*.csproj'
        vstsFeed:   $(vstsFeed)

# ==========================================================================
# BOOTSTRAP VALIDATION, STAGE: CI_BOOTSTRAP_INIT
# SKULL & CROSS-BONES - DO NOT COMMENT OUT, OR REMOVE THIS SECTION
# ==========================================================================
    - template: /templates/boot-strap.yml@CeBlueprints
      parameters:
        bootstrapMode:        'init'
        applicationType:      'dotnet'
        applicationBlueprint: ${{parameters.applicationBlueprint}}
        portfolioName:        ${{parameters.portfolioName}}
        productName:          ${{parameters.productName}}
        sourcesDirectory:     $(Build.SourcesDirectory)
        verbose:              ${{parameters.verbose}}
        modeElite:            ${{parameters.modeElite}}

# ==========================================================================

# --------------------------------------------------------------------------
# CONTINUOUS INTEGRATION BUILD
# --------------------------------------------------------------------------
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command:    'build'
        projects:   '**/${{parameters.azFuncProjectName}}.csproj'
        arguments:  '--configuration $(buildConfiguration) --no-restore'

# --------------------------------------------------------------------------
# CONTINUOUS INTEGRATION TEST
# --------------------------------------------------------------------------
    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command:    'test'
        projects:   '**/*Tests/*.csproj'
        arguments:  '--configuration $(buildConfiguration) --no-restore'

# --------------------------------------------------------------------------
# PUBLISH
# --------------------------------------------------------------------------
    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command:            'publish'
        publishWebProjects: false
        projects:           '**/${{parameters.azFuncProjectName}}.csproj'
        arguments:          '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-restore'
        zipAfterPublish:    true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish:  '$(Build.ArtifactStagingDirectory)'
        ArtifactName:   'drop'

# ==========================================================================
# BOOTSTRAP VALIDATION, BUILDIGNCODE ONLY
# SKULL & CROSS-BONES - DO NOT COMMENT OUT, OR REMOVE THIS SECTION
# ==========================================================================
    - template: /templates/boot-strap.yml@CeBlueprints
      parameters:
        bootstrapMode:        'run'
        applicationType:      'dotnet'
        applicationBlueprint: ${{parameters.applicationBlueprint}}
        portfolioName:        ${{parameters.portfolioName}}
        productName:          ${{parameters.productName}}
        sourcesDirectory:     $(Build.SourcesDirectory)
        verbose:              ${{parameters.verbose}}
        modeElite:            ${{parameters.modeElite}}
# ==========================================================================

# --------------------------------------------------------------------------
# END OF BUILD and TEST STAGE
# --------------------------------------------------------------------------

    - ${{ if eq(lower(variables['Build.SourceBranchName']), 'merge') }}:
      - script: echo CD part of the pipeline is suppressed for pull request validation builds! 
        displayName: PR Validation CD Suppression Alert