variables:

# -----------------------------------------------------------------------------------------------------
#
# If you are not going to use all stages, as below, you can suppress them by setting active to false.
#
# Need help with the configuration?
#
# -VARIABLE ---------- VALUE ------
# *Active              true or false. To disable or hide a stage, set value to false.
# *EnvName             See https://dev.azure.com/<__AzDO_ORG__>/<__AzDO_PROJECT__>/_environments
#                      Format: <portfolio>-<stage-name>-<stage-name-acronym>, for example
#                      assessments-development-dv
# *VmImage            ubuntu-latest, windows-latest, 
#                      or see https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
# *other*              Contact your Delivery CSE.
#
# -----------------------------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------------------------
# Development Stage
- name:  developmentStageActive
  value: true
- name:  developmentStageEnvName
  value: '<tbd>'
- name:  developmentStageVmImage
  value: '<tbd>'
- name:  developmentStageAzRmWebDeployAzureSubscription
  value: '<TBD>'
- name:  developmentStageAzResourceGroup
  value: '<TBD>'
- name:  developmentStageAzRmWebDeployWebAppName
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# System Test Stage
- name:  systemTestStageActive
  value: false
- name:  systemTestStageEnvName
  value: '<tbd>'
- name:  systemTestStageVmImage
  value: '<tbd>'
- name:  systemTestStageAzRmWebDeployAzureSubscription
  value: '<TBD>'
- name:  systemTestStageAzResourceGroup
  value: '<TBD>'
- name:  systemTestStageAzRmWebDeployWebAppName
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Staging Stage
# -----------------------------------------------------------------------------------------------------
# Staging Stage
- name:  stagingStageActive
  value: false
- name:  stagingStageEnvName
  value: '<tbd>'
- name:  stagingStageVmImage
  value: '<tbd>'
- name:  stagingStageAzRmWebDeployAzureSubscription
  value: '<TBD>'
- name:  stagingStageAzResourceGroup
  value: '<TBD>'
- name:  stagingStageAzRmWebDeployWebAppName
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Production Stage-
- name:  productionStageActive
  value: false
- name:  productionStageEnvName
  value: '<tbd>'
- name:  productionStageVmImage
  value: '<tbd>'
- name:  productionStageAzRmWebDeployAzureSubscription
  value: '<TBD>'
- name:  productionStageAzResourceGroup
  value: '<TBD>'
- name:  productionStageAzRmWebDeployWebAppName
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Production Central Stage
# Introduced with version blueprintVersion 2.1.1
- name:  productionCanadaCentralStageActive
  value: false
- name:  productionCanadaCentralStageEnvName
  value: '<tbd>'
- name:  productionCanadaCentralStageVmImage
  value: '<tbd>'
- name:  productionCanadaCentralStageAzRmWebDeployAzureSubscription
  value: '<TBD>'
- name:  productionCanadaCentralStageAzResourceGroup
  value: '<TBD>'
- name:  productionCanadaCentralStageAzRmWebDeployWebAppName
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Production East Stage
# Introduced with version blueprintVersion 2.1.1
- name:  productionCanadaEastStageActive
  value: false
- name:  productionCanadaEastStageEnvName
  value: '<tbd>'
- name:  productionCanadaEastStageVmImage
  value: '<tbd>'
- name:  productionCanadaEastStageAzRmWebDeployAzureSubscription
  value: '<TBD>'
- name:  productionCanadaEastStageAzResourceGroup
  value: '<TBD>'
- name:  productionCanadaEastStageAzRmWebDeployWebAppName
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# @@START: SKULL-AND-CROSS BONES AREA
# Introduced with version blueprintVersion 2.1.1
# Be very, very careful when making changes to the configuration below!
# -----------------------------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------------------------
# Security Review Stage
- name:  securityReviewStageEnvName
  value: '<tbd>'

# -----------------------------------------------------------------------------------------------------
# @@END: SKULL-AND-CROSS BONES AREA
# Introduced with version blueprintVersion 2.1.1
# -----------------------------------------------------------------------------------------------------