parameters:
- name:     stage
  type:     object

stages:

# -----------------------------------------------------------------------------------------------------
# DEVELOPMENT STAGE
# -----------------------------------------------------------------------------------------------------
- ${{ if eq(parameters.stage.development.config.active, true) }}:
  - template: /blueprints/webapp/azure-pipeline-webapp-cd-stage.yml@CeBlueprints
    parameters:
      name:                         'Development'
      displayName:                  'Development (DV)'
      config:                       ${{parameters.stage.development.config}}
      dependsOn:
      - ContinuousIntegration

# -----------------------------------------------------------------------------------------------------
# SYSTEM TEST STAGE
# -----------------------------------------------------------------------------------------------------
- ${{ if eq(parameters.stage.systemTest.config.active, true) }}:
  - template: /blueprints/webapp/azure-pipeline-webapp-cd-stage.yml@CeBlueprints
    parameters:
      name:                         'SystemTest'
      displayName:                  'System Test (SY)'
      config:                       ${{parameters.stage.systemTest.config}}
      dependsOn:
      - ContinuousIntegration
      - ${{ if eq(parameters.stage.development.config.active, true) }}:
        - Development

# -----------------------------------------------------------------------------------------------------
# SECURITY AUTOMATION STAGE
# -----------------------------------------------------------------------------------------------------
- template: /templates/dev-sec-ops/azure-pipeline-security-auto.yml@CeBlueprints
  parameters:
    name:                  'SecurityAutomation'
    displayName:           'Security Automation (SA)'
    config:                ${{parameters.stage.securityAutomation.config}}
    applicationBlueprint:  ${{parameters.stage.securityAutomation.applicationBlueprint}}
    blueprintVersion:      ${{parameters.stage.securityAutomation.blueprintVersion}}
    modeElite:             ${{parameters.stage.securityAutomation.modeElite}}
    dependsOn:
    - ContinuousIntegration
    - ${{ if eq(parameters.stage.development.config.active, true) }}:
      - Development
    - ${{ if eq(parameters.stage.systemTest.config.active, true) }}:
      - SystemTest

# -----------------------------------------------------------------------------------------------------
# QA AUTOMATION STAGE
# -----------------------------------------------------------------------------------------------------
- template: /templates/qa/azure-pipeline-qa-scans.yml@CeBlueprints
  parameters:
    name:                 'QAAutomation'
    displayName:          'QA Automation (QAA)'
    config:               ${{parameters.stage.qaAutomation.config}}
    applicationBlueprint: ${{parameters.stage.qaAutomation.applicationBlueprint}}
    blueprintVersion:     ${{parameters.stage.qaAutomation.blueprintVersion}}
    modeElite:            ${{parameters.stage.qaAutomation.modeElite}}
    dependsOn:
    - ContinuousIntegration
    - ${{ if eq(parameters.stage.development.config.active, true) }}:
      - Development
    - ${{ if eq(parameters.stage.systemTest.config.active, true) }}:
      - SystemTest

# -----------------------------------------------------------------------------------------------------
# SECURITY REVIEW STAGE
# -----------------------------------------------------------------------------------------------------
- ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
  - template: /templates/dev-sec-ops/azure-pipeline-security-review.yml@CeBlueprints
    parameters:
      name:                 'SecurityReview'
      displayName:          'Security Review (SR)'
      config:               ${{parameters.stage.securityReview.config}}
      applicationBlueprint: ${{parameters.stage.securityReview.applicationBlueprint}}
      blueprintVersion:     ${{parameters.stage.securityReview.blueprintVersion}}
      modeElite:            ${{parameters.stage.securityReview.modeElite}}
      dependsOn:
      - ContinuousIntegration
      - ${{ if eq(parameters.stage.development.config.active, true) }}:
        - Development
      - ${{ if eq(parameters.stage.systemTest.config.active, true) }}:
        - SystemTest
      - SecurityAutomation

# -----------------------------------------------------------------------------------------------------
# STAGING STAGE
# -----------------------------------------------------------------------------------------------------
- ${{ if and(eq(parameters.stage.staging.config.active, true), or(eq(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))) }}:
  - template: /blueprints/webapp/azure-pipeline-webapp-cd-stage.yml@CeBlueprints
    parameters:
      name:                         'Staging'
      displayName:                  'Staging (ST)'
      config:                       ${{parameters.stage.staging.config}}
      dependsOn:
      - ContinuousIntegration
      - ${{ if eq(parameters.stage.development.config.active, true) }}:
        - Development
      - ${{ if eq(parameters.stage.systemTest.config.active, true) }}:
        - SystemTest
      - QAAutomation
      - SecurityAutomation
      - SecurityReview

# -----------------------------------------------------------------------------------------------------
# PRE-PROD AUTOMATION SCANS STAGE
# -----------------------------------------------------------------------------------------------------
- ${{ if and( or(eq(parameters.stage.production.config.active, true),eq(parameters.stage.productionCanadaCentral.config.active, true), eq(parameters.stage.productionCanadaEast.config.active, true)), or(eq(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))) }}:
  - template: /templates/pre-prod/azure-pipeline-pre-prod-automation.yml@CeBlueprints
    parameters:
      name:                 'PreProdAutomation'
      displayName:          'Pre-Prod Automation (PPA)'
      config:               ${{parameters.stage.preProdAutomation.config}}
      applicationBlueprint: ${{parameters.stage.preProdAutomation.applicationBlueprint}}
      blueprintVersion:     ${{parameters.stage.preProdAutomation.blueprintVersion}}
      modeElite:            ${{parameters.stage.preProdAutomation.modeElite}}
      dependsOn:
      - ContinuousIntegration
      - ${{ if eq(parameters.stage.development.config.active, true) }}:
        - Development
      - ${{ if eq(parameters.stage.systemTest.config.active, true) }}:
        - SystemTest
      - QAAutomation
      - SecurityAutomation
      - SecurityReview
      - ${{ if eq(parameters.stage.staging.config.active, true) }}:
        - Staging

# -----------------------------------------------------------------------------------------------------
# PRODUCTION STAGE
# -----------------------------------------------------------------------------------------------------
- ${{ if and(eq(parameters.stage.production.config.active, true), or(eq(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))) }}:
  - template: /blueprints/webapp/azure-pipeline-webapp-cd-stage.yml@CeBlueprints
    parameters:
      name:                         'Production'
      displayName:                  'Production (PR)'
      config:                       ${{parameters.stage.production.config}}
      dependsOn:
      - ContinuousIntegration
      - ${{ if eq(parameters.stage.development.config.active, true) }}:
        - Development
      - ${{ if eq(parameters.stage.systemTest.config.active, true) }}:
        - SystemTest
      - QAAutomation
      - SecurityAutomation
      - SecurityReview
      - ${{ if eq(parameters.stage.staging.config.active, true) }}:
        - Staging
      - PreProdAutomation

- ${{ if and(eq(parameters.stage.productionCanadaCentral.config.active, true), or(eq(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))) }}:
  - template: /blueprints/webapp/azure-pipeline-webapp-cd-stage.yml@CeBlueprints
    parameters:
      name:                         'ProductionCanadaCentral'
      displayName:                  'Prod Canada Central (CC-PR)'
      config:                       ${{parameters.stage.productionCanadaCentral.config}}
      dependsOn:
      - ContinuousIntegration
      - ${{ if eq(parameters.stage.development.config.active, true) }}:
        - Development
      - ${{ if eq(parameters.stage.systemTest.config.active, true) }}:
        - SystemTest
      - QAAutomation
      - SecurityAutomation
      - SecurityReview
      - ${{ if eq(parameters.stage.staging.config.active, true) }}:
        - Staging
      - PreProdAutomation

- ${{ if and(eq(parameters.stage.productionCanadaEast.config.active, true), or(eq(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))) }}:
  - template: /blueprints/webapp/azure-pipeline-webapp-cd-stage.yml@CeBlueprints
    parameters:
      name:                         'ProductionCanadaEast'
      displayName:                  'Prod Canada East (CE-PR)'
      config:                       ${{parameters.stage.productionCanadaEast.config}}
      dependsOn:
      - ContinuousIntegration
      - ${{ if eq(parameters.stage.development.config.active, true) }}:
        - Development
      - ${{ if eq(parameters.stage.systemTest.config.active, true) }}:
        - SystemTest
      - QAAutomation
      - SecurityAutomation
      - SecurityReview
      - ${{ if eq(parameters.stage.staging.config.active, true) }}:
        - Staging
      - PreProdAutomation