parameters:
- name:     portfolioName
  type:     string
- name:     productName
  type:     string
- name:     publishFolder
  type:     string
- name:     applicationBlueprint
  type:     string
  default:  '__101__'
- name:     modeElite
  type:     boolean
  default:  false
  # Bootstrap optionals
- name:     verbose
  type:     boolean
  default:  false
# CI Blueprint optionals
- name:     versionSpec
  type:     string
  default:  '5.6.3' #interim hotfix until we fix latest git tools versions
# CD Blueprint optionals
- name:     suppressCD
  type:     boolean
  default:  false

# VARIABLES
variables:
- ${{ if ne(parameters.suppressCD, true) }}:
  - template: /deploy/${{ lower(parameters.portfolioName) }}/${{ lower(parameters.productName) }}-config.yml@CeConfiguration

stages:

# --------------------------------------------------------------------------
# START OF PIPELINE
# --------------------------------------------------------------------------
- template: /blueprints/__101__/azure-pipeline-__101__-ci.yml@CeBlueprints
  parameters:
    portfolioName:        ${{parameters.portfolioName}}
    productName:          ${{parameters.productName}}
    applicationBlueprint: ${{parameters.applicationBlueprint}}
    verbose:              ${{parameters.verbose}}
    modeElite:            ${{parameters.modeElite}}
    versionSpec:          ${{parameters.versionSpec}}

# --------------------------------------------------------------------------
# DEPLOYMENT
# 2021.10.04 WS Suppress CD on "merge" so that we can use PR validation builds
# --------------------------------------------------------------------------
- ${{ if and(ne(parameters.suppressCD, true), ne(lower(variables['Build.SourceBranchName']), 'merge')) }}:
  - template: /blueprints/__101__/azure-pipeline-__101__-cd.yml@CeBlueprints
    parameters:
      stage:
        development:
          name:                           ${{variables.developmentStageName}}
          vmImage:                        ${{variables.developmentStageVmImage}}
          envName:                        ${{variables.developmentStageEnvName}}
          applicationBlueprint:           ${{parameters.applicationBlueprint}}                         
          modeElite:                      ${{parameters.modeElite}}
# TODO pass your configuration variables here
        systemTest:
          name:                           ${{variables.systemTestStageName}}
          vmImage:                        ${{variables.systemTestStageVmImage}}
          envName:                        ${{variables.systemTestStageEnvName}}
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
# TODO pass your configuration variables here
        staging:
          name:                           ${{variables.stagingStageName}}
          vmImage:                        ${{variables.stagingStageVmImage}}
          envName:                        ${{variables.stagingStageEnvName}}
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
# TODO pass your configuration variables here
        production:
          name:                           ${{variables.productionStageName}}
          vmImage:                        ${{variables.productionStageVmImage}}
          envName:                        ${{variables.productionStageEnvName}}
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
# TODO pass your configuration variables here 
        securityReview:
          envName:                        ${{variables.securityReviewStageEnvName}}
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
        securityScans:
          applicationBlueprint:           ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}
        qaScans:
          applicationBlueprint:            ${{parameters.applicationBlueprint}}
          modeElite:                      ${{parameters.modeElite}}

# --------------------------------------------------------------------------
# END OF PIPELINE
# --------------------------------------------------------------------------
