parameters:
- name:     name
  type:     string
- name:     displayName
  type:     string
- name:     config
  type:     object
  default:  []
- name:     dependsOn
  type:     object
  default:  []

stages:

# -----------------------------------------------------------------------------------------------------
# STAGE
# -----------------------------------------------------------------------------------------------------

- stage:         ${{parameters.name}}
  displayName:   ${{parameters.displayName}}
  ${{ if ne(length(parameters.dependsOn), 0) }}:
    dependsOn:
      - ${{ each stage in parameters.dependsOn }}:
        - ${{stage}}
  variables:
      currentVersion: $[ stageDependencies.ContinuousIntegration.ContinuousIntegration.outputs['setSemVersion.semVersion'] ]
  ${{ if ne(parameters.config.nameVM, '') }}: #910188
    pool:
      name:      ${{parameters.config.namePool}}
      vmImage:   ${{parameters.config.nameVM}}
  ${{ else }}:
    pool:
      name:      ${{parameters.config.namePool}}
  jobs:
  - deployment:  ${{parameters.name}}
    environment: ${{parameters.config.envName}}
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo name = ${{parameters.name}}
          - script: echo testData = ${{parameters.config.testData}}

