variables:

# -----------------------------------------------------------------------------------------------------
# Security Review Stage
# -----------------------------------------------------------------------------------------------------
- name:  securityReviewStageEnvName
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# System Test Stage
# -----------------------------------------------------------------------------------------------------
- name:  systemTestStageActive
  value: true
- name:  systemTestStageEnvName
  value: '<TBD>'
- name:  systemTestStageVmImage
  value: '<TBD>'
- name:  systemTestTargetFeed
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Production Stage
# -----------------------------------------------------------------------------------------------------
- name:  productionStageActive
  value: true
- name:  productionStageEnvName
  value: '<TBD>'
- name:  productionStageVmImage
  value: '<TBD>'
- name:  productionTargetFeed
  value: '<TBD>'
