variables:

# -----------------------------------------------------------------------------------------------------
#
# If you are not going to use all stages, as below, you can suppress them by setting active to false.
#
# Need help with the configuration?
#
# -VARIABLE ---------- VALUE ------
# *Active              true or false. To disable or hide a stage, set value to false.
# *EnvName             See https://dev.azure.com/wcbbc/IT-App-Delivery/_environments
#                      Format: <portfolio>-<stage-name>-<stage-name-acronym>, for example
#                      assessments-development-dv
# *VmImage             ubuntu-latest, windows-latest, 
#                      or see https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
# *other*              Contact your Delivery CSE.
#
# -----------------------------------------------------------------------------------------------------


# -----------------------------------------------------------------------------------------------------
# System Test Stage
# -----------------------------------------------------------------------------------------------------
- name:  systemTestStageActive
  value: true
- name:  systemTestStageEnvName
  value: '<TBD>'
- name:  systemTestStageVmImage
  value: '<TBD>'
- name:  systemTestTargetFeed
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Production Stage
# -----------------------------------------------------------------------------------------------------
- name:  productionStageActive
  value: false
- name:  productionStageEnvName
  value: '<TBD>'
- name:  productionStageVmImage
  value: '<TBD>'
- name:  productionTargetFeed
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Production Central Stage
# Introduced with version blueprintVersion 2.1.1
- name:  productionCanadaCentralStageActive
  value: false
- name:  productionCanadaCentralStageEnvName
  value: '<tbd>'
- name:  productionCanadaCentralStageVmImage
  value: '<tbd>'
- name:  productionCanadaCentralStageTargetFeed
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Production East Stage
# Introduced with version blueprintVersion 2.1.1
- name:  productionCanadaEastStageActive
  value: false
- name:  productionCanadaEastStageEnvName
  value: '<tbd>'
- name:  productionCanadaEastStageVmImage
  value: '<tbd>'
- name:  productionCanadaEastStageTargetFeed
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# @@START: SKULL-AND-CROSS BONES AREA
# Introduced with version blueprintVersion 2.1.1
# Be very, very careful when making changes to the configuration below!
# -----------------------------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------------------------
# Security Review Stage
- name:  securityReviewStageEnvName
  value: '<tbd>'

# -----------------------------------------------------------------------------------------------------
# @@END: SKULL-AND-CROSS BONES AREA
# Introduced with version blueprintVersion 2.1.1
# -----------------------------------------------------------------------------------------------------